Repository MultimodalUniverse/MultimodalUniverse, pull requests merged in 2024-12, with the labels that each got.

#128 V1/jwst debug
  scripts/jwst/README.md
  scripts/jwst/build_parent_sample.py
  scripts/jwst/info.py
  scripts/jwst/jwst.py
  scripts/jwst/test.sh
Labels: Dataset, Galaxies

#146 Updating HF Upload Script (Addressing #145)
  scripts/upload_to_hub.py
Labels: infrastructure

#154 update galah prep scripts
  scripts/galah/README.md
  scripts/galah/build_parent_sample.py
  scripts/galah/download.py
  scripts/galah/galah.py
  scripts/galah/prepare.sh
  scripts/galah/test.sh
  scripts/galah/test_load.py
Labels: Dataset, Spectra, Stars

#155 bug fix
  scripts/galah/test.sh
Labels: bug
