Repository MultimodalUniverse/MultimodalUniverse, pull requests merged in 2024-11, with the labels that each got.

#129 V1/manga debug
  scripts/manga/build_parent_sample.py
  scripts/manga/manga.py
Labels: Dataset, IFU

#135 apogee updates
  scripts/apogee/README.md
  scripts/apogee/build_parent_sample.py
  scripts/apogee/download.sh
Labels: Dataset

#24 Add GALAH dataset
  dset-requirements.txt
  scripts/galah/README.md
  scripts/galah/build_parent_sample.py
  scripts/galah/galah.py
  scripts/galah/test.sh
Labels: Dataset, Spectra, Stars

#82 Photometric Classification Baseline using snmachine
  baselines/photo_class/README
  baselines/photo_class/snmachine_example.py
  dset-requirements.txt
Labels: Time Series, Supernovae, Baselines

#137 CFA unification
  scripts/Makefile
  scripts/cfa/build_parent_sample.py
  scripts/cfa/cfa.py
  scripts/cfa/cfa3.py
  scripts/cfa/cfa_SECCSN.py
  scripts/cfa/cfa_snII.py
  scripts/cfa/download_data.py
  scripts/cfa/test.sh
Labels: Dataset, Supernovae

#139 csp: Train files from healpix substructure
  scripts/csp/csp.py
  scripts/csp/test.sh
Labels: Dataset, Supernovae

#140 Information Retrieval: Making Citing and Acknowledgements Easy
  DESIGN.md
  README.md
  scripts/apogee/apogee.py
  scripts/btsbot/btsbot.py
  scripts/chandra/chandra.py
  scripts/csp/csp.py
  scripts/des_y3_sne_ia/des_y3_sne_ia.py
  scripts/desi/desi.py
  scripts/desi_provabgs/desi_provabgs.py
  scripts/foundation/foundation.py
  scripts/gaia/gaia.py
  scripts/galah/galah.py
  scripts/gz10/gz10.py
  scripts/hsc/hsc.py
  scripts/info.py
  scripts/jwst/jwst.py
  scripts/legacysurvey/legacysurvey.py
  scripts/manga/manga.py
  scripts/plasticc/plasticc.py
  scripts/ps1_sne_ia/ps1_sne_ia.py
  scripts/sdss/sdss.py
  scripts/snls/snls.py
  scripts/ssl_legacysurvey/ssl_legacysurvey.py
  scripts/swift_sne_ia/swift_sne_ia.py
  scripts/tess/tess.py
  scripts/vipers/vipers.py
  scripts/yse/yse.py
Labels: documentation, enhancement, infrastructure

#143 Fix name: astropile vs mmu
  scripts/desi/desi.py
  scripts/gz10/build_parent_sample.py
  scripts/gz10/gz10.py
  scripts/hsc/hsc.py
  scripts/jwst/build_parent_sample.py
  scripts/jwst/jwst.py
  scripts/legacysurvey/legacysurvey.py
  scripts/manga/manga.py
  scripts/ssl_legacysurvey/ssl_legacysurvey.py
  scripts/vipers/build_parent_sample.py
  scripts/vipers/vipers.py
Labels: documentation, infrastructure
