Repository MultimodalUniverse/MultimodalUniverse, pull requests merged in 2024-05, with the labels that each got.

#51 5 Type Ia Supernova Datasets From PantheonPlusSH0ES
  .gitignore
  dset-requirements.txt
  scripts/des_y3_sne_ia/DES3YR_DES_LIST.txt
  scripts/des_y3_sne_ia/README.md
  scripts/des_y3_sne_ia/build_parent_sample.py
  scripts/des_y3_sne_ia/des_y3_sne_ia.py
  scripts/des_y3_sne_ia/download_data.py
  scripts/des_y3_sne_ia/test.sh
  scripts/foundation/Foundation_DR1_list.txt
  scripts/foundation/README.md
  scripts/foundation/build_parent_sample.py
  scripts/foundation/download_data.py
  scripts/foundation/foundation.py
  scripts/foundation/test.sh
  scripts/ps1_sne_ia/PS1_LIST.txt
  scripts/ps1_sne_ia/README.md
  scripts/ps1_sne_ia/build_parent_sample.py
  scripts/ps1_sne_ia/download_data.py
  scripts/ps1_sne_ia/ps1_sne_ia.py
  scripts/ps1_sne_ia/test.sh
  scripts/snls/README.md
  scripts/snls/SNLS_LIST.txt
  scripts/snls/build_parent_sample.py
  scripts/snls/download_data.py
  scripts/snls/snls.py
  scripts/snls/test.sh
  scripts/swift_sne_ia/README.md
  scripts/swift_sne_ia/SWIFT_LIST.txt
  scripts/swift_sne_ia/build_parent_sample.py
  scripts/swift_sne_ia/download_data.py
  scripts/swift_sne_ia/swift_sne_ia.py
  scripts/swift_sne_ia/test.sh
Labels: Dataset, Time Series, Supernovae

#66 Fix Globus transfer for DESI dataset
  scripts/desi/README.md
  scripts/desi/globus_transfer.py
Labels: documentation, Dataset

#50 BTSbot
  scripts/btsbot/README.md
  scripts/btsbot/_get_features.py
  scripts/btsbot/_make_tiny_download.py
  scripts/btsbot/btsbot.py
  scripts/btsbot/build_parent_sample.py
  scripts/btsbot/download_data.py
  scripts/btsbot/test.sh
Labels: Dataset, Images, Time Series, Supernovae, v0

#74 Implements a few efficiency tweaks to speed up file operations (including standardizing healpix_nside=16)
  scripts/apogee/apogee.py
  scripts/apogee/build_parent_sample.py
  scripts/btsbot/btsbot.py
  scripts/btsbot/build_parent_sample.py
  scripts/decals/build_parent_sample.py
  scripts/decals/decals.py
  scripts/des_y3_sne_ia/build_parent_sample.py
  scripts/des_y3_sne_ia/des_y3_sne_ia.py
  scripts/desi/build_parent_sample.py
  scripts/desi/desi.py
  scripts/desi_provabgs/build_parent_sample.py
  scripts/foundation/build_parent_sample.py
  scripts/foundation/foundation.py
  scripts/gaia/gaia.py
  scripts/gaia/healpixify.py
  scripts/gz10/build_parent_sample.py
  scripts/hsc/build_parent_sample.py
  scripts/hsc/hsc.py
  scripts/jwst/build_parent_sample.py
  scripts/jwst/jwst.py
  scripts/plasticc/build_parent_sample.py
  scripts/plasticc/plasticc.py
  scripts/ps1_sne_ia/build_parent_sample.py
  scripts/ps1_sne_ia/ps1_sne_ia.py
  scripts/sdss/build_parent_sample.py
  scripts/sdss/sdss.py
  scripts/snls/build_parent_sample.py
  scripts/snls/snls.py
  scripts/swift_sne_ia/build_parent_sample.py
  scripts/swift_sne_ia/swift_sne_ia.py
  scripts/yse/build_parent_sample.py
  scripts/yse/yse.py
Labels: enhancement, infrastructure

#53 Adding 4 Harvard Center for Astronomy datasets.
  .gitignore
  scripts/cfa/CFA3_4SH_COORDS.txt
  scripts/cfa/CFA3_COORDS.txt
  scripts/cfa/CFA4_COORDS.txt
  scripts/cfa/CFA_SNII_COORDS.txt
  scripts/cfa/build_parent_sample.py
  scripts/cfa/cfa3.py
  scripts/cfa/cfa3_4sh.py
  scripts/cfa/cfa4.py
  scripts/cfa/cfa_snII.py
  scripts/cfa/download_data.py
  scripts/cfa/info.dat
  scripts/cfa/test.sh
Labels: Dataset, Time Series, Supernovae

#20 VIPERS download and standardization script
  scripts/vipers/README.md
  scripts/vipers/build_parent_sample.py
  scripts/vipers/test.sh
  scripts/vipers/vipers.py
Labels: Dataset, Spectra, Galaxies

#58 Readme Update and All Contributors Guidelines Adoption
  .all-contributorsrc
  README.md
  assets/astropile.png
Labels: documentation, infrastructure

#40 [DATA] Add TESS light curves
  dset-requirements.txt
  scripts/tess/README.md
  scripts/tess/build_parent_sample.py
  scripts/tess/mast_s3_transfer.py
  scripts/tess/quality.py
  scripts/tess/tess.py
  scripts/tess/test.sh
Labels: Dataset, Stars, Time Series

#27 Adding Chandra x-ray data download script and ancillary files
  dset-requirements.txt
  scripts/chandra/README.md
  scripts/chandra/build_parent_sample.py
  scripts/chandra/chandra.py
  scripts/chandra/download_script.py
  scripts/chandra/test.sh
Labels: Dataset, xray

#33 Adds MaNGA IFU support
  scripts/manga/README.md
  scripts/manga/access_transfer.py
  scripts/manga/build_parent_sample.py
  scripts/manga/demo_manga.ipynb
  scripts/manga/globus_transfer.py
  scripts/manga/manga.py
  scripts/manga/test.sh
Labels: enhancement, Dataset, Galaxies, IFU
