Repository MultimodalUniverse/MultimodalUniverse, pull requests merged in 2024-04, with the labels that each got.

#32 [Infrastructure] Add master catalogue
  .gitignore
  astropile/utils.py
Labels: enhancement, infrastructure

#22 download PLAsTiCC data and convert to HDF5
  notebooks/plasticc_demo.ipynb
  scripts/plasticc/build_parent_sample.py
  scripts/plasticc/plasticc.py
  scripts/plasticc/test.sh
Labels: Dataset, Time Series, Simulation

#29 Add Gaia DR3
  scripts/gaia/README.md
  scripts/gaia/coeff_file_list.txt
  scripts/gaia/download_parts.py
  scripts/gaia/gaia.py
  scripts/gaia/healpixify.py
  scripts/gaia/merge_parts.py
  scripts/gaia/source_file_list.txt
  scripts/gaia/test.sh
  scripts/gaia/test_load.py
Labels: Dataset, Stars

#21 Add initial APOGEE DR17 support
  scripts/apogee/README.md
  scripts/apogee/apogee.py
  scripts/apogee/build_parent_sample.py
  scripts/apogee/test.sh
Labels: Dataset, Stars, v0

#42 Add JWST data
  .gitignore
  dset-requirements.txt
  scripts/jwst/README.md
  scripts/jwst/build_parent_sample.py
  scripts/jwst/jwst.py
  scripts/jwst/test.sh
Labels: v0

#46 YSE
  dset-requirements.txt
  scripts/yse/README.md
  scripts/yse/build_parent_sample.py
  scripts/yse/download_data.py
  scripts/yse/test.sh
  scripts/yse/yse.py
Labels: v0
